### ISSUE TITLE
Duplicated GADM_IDs appeared in gadm_shapes

### ISSUE THREAD

**Issue by CUIJING03** [pz-max/pypsa-africa#1094]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.

- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

When I updated to version` 0.4.0`, I found that the rule `build_bus_regions` does not work. The associated logs indicated the error as `ValueError: All arrays must be of the same length`. after debugging `build_bus_regions.py` I found that there were multiple duplicate GADM_IDs appearing (as shown here). One additional point I would like to add, I used alternative_clustering.

The first figure shows the specifics of a pair of duplicate GADM_IDs, and the second figure embodies all the duplicate GADM_IDs
![gadm_shapes](https://github.com/user-attachments/assets/695234e0-3223-4033-bee8-2cf0fd04851b)
![307c71792de240045ba557debe2b311](https://github.com/user-attachments/assets/49c08cfa-9f69-444a-9741-132a6e32588c)

**Comment by CUIJING03** [comment]
My build_bus_regions log is as follows:
```
INFO:pypsa.io:Imported network base.nc has buses, lines, links, transformers
ERROR:_helpers:An error happened in module 'D:\\Anaconda3\\envs\\pypsa-earth\\lib\\site-packages\\pandas\\core\\internals\\construction.py', function '_extract_index': All arrays must be of the same length
Traceback (most recent call last):
  File "D:\pypsa-earth-project\pypsa-earth\.snakemake\scripts\tmpmtwwtd5g.build_bus_regions.py", line 205, in <module>
    temp_region = gpd.GeoDataFrame(
  File "D:\Anaconda3\envs\pypsa-earth\lib\site-packages\geopandas\geodataframe.py", line 139, in __init__
    super().__init__(data, *args, **kwargs)
  File "D:\Anaconda3\envs\pypsa-earth\lib\site-packages\pandas\core\frame.py", line 778, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "D:\Anaconda3\envs\pypsa-earth\lib\site-packages\pandas\core\internals\construction.py", line 503, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "D:\Anaconda3\envs\pypsa-earth\lib\site-packages\pandas\core\internals\construction.py", line 114, in arrays_to_mgr
    index = _extract_index(arrays)
  File "D:\Anaconda3\envs\pypsa-earth\lib\site-packages\pandas\core\internals\construction.py", line 677, in _extract_index
    raise ValueError("All arrays must be of the same length")
ValueError: All arrays must be of the same length
```

**Comment by davide-f** [comment]
Great spot @CUIJING03 !
You may check if this code works:
https://github.com/pypsa-meets-earth/pypsa-earth/blob/1bd7f84f1f9b0e081d790ffa198729076fd923b6/scripts/build_shapes.py#L1292-L1297

Moreover if you open a PR about it, it would be great if you could move this fix into the function filder_gadm
https://github.com/pypsa-meets-earth/pypsa-earth/blob/1bd7f84f1f9b0e081d790ffa198729076fd923b6/scripts/build_shapes.py#L126
