### ISSUE TITLE
Solve_sector_network not solvable with GLPK

### ISSUE THREAD

**Issue by GbotemiB** [pz-max/pypsa-africa#1117]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug
Running solve_sector_network with other solver that is not gurobi doesn't work. I tried using cplex and glpk.
*Please provide a description of what the bug is and add a minimal example/command for reproducing the bug.*

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

CPLEX
```bash
[Thu Sep 26 22:37:51 2024]
rule cluster_network:
    input: networks/tutorial/elec_s.nc, resources/tutorial/shapes/country_shapes.geojson, resources/tutorial/bus_regions/regions_onshore_elec_s.geojson, resources/tutorial/bus_regions/regions_offshore_elec_s.geojson, resources/tutorial/shapes/gadm_shapes.geojson, data/costs.csv
    output: networks/tutorial/elec_s_6.nc, resources/tutorial/bus_regions/regions_onshore_elec_s_6.geojson, resources/tutorial/bus_regions/regions_offshore_elec_s_6.geojson, resources/tutorial/bus_regions/busmap_elec_s_6.csv, resources/tutorial/bus_regions/linemap_elec_s_6.csv
    log: logs/tutorial/cluster_network/elec_s_6.log
    jobid: 8
    benchmark: benchmarks/tutorial/cluster_network/elec_s_6
    reason: Input files updated by another job: networks/tutorial/elec_s.nc, resources/tutorial/bus_regions/regions_onshore_elec_s.geojson, resources/tutorial/shapes/gadm_shapes.geojson, resources/tutorial/shapes/country_shapes.geojson, resources/tutorial/bus_regions/regions_offshore_elec_s.geojson
    wildcards: simpl=, clusters=6
    resources: tmpdir=/var/folders/c3/657p__892k72qxh6r8fdkqsh0000gn/T, mem_mb=3000, mem_mib=2862

/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pypsa/networkclustering.py:16: UserWarning: The namespace `pypsa.networkclustering` is deprecated and will be removed in PyPSA v0.24. Please use `pypsa.clustering.spatial instead`. 
  warnings.warn(
/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pypsa/components.py:318: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attrs.loc[bool_b, "default"] = attrs.loc[bool_b].isin({True, "True"})
/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pypsa/components.py:318: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attrs.loc[bool_b, "default"] = attrs.loc[bool_b].isin({True, "True"})
/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pypsa/components.py:318: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attrs.loc[bool_b, "default"] = attrs.loc[bool_b].isin({True, "True"})
/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pypsa/components.py:318: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attrs.loc[bool_b, "default"] = attrs.loc[bool_b].isin({True, "True"})
INFO:pypsa.io:Imported network elec_s.nc has buses, carriers, generators, lines, loads, storage_units
Overwriting marginal_cost of Index(['solar', 'onwind', 'offwind', 'hydro', 'H2', 'electrolysis',
       'fuel cell', 'battery', 'battery inverter'],
      dtype='object') to [0.01  0.015 0.015 0.    0.    0.    0.    0.    0.   ]
INFO:add_electricity:Overwriting marginal_cost of Index(['solar', 'onwind', 'offwind', 'hydro', 'H2', 'electrolysis',
       'fuel cell', 'battery', 'battery inverter'],
      dtype='object') to [0.01  0.015 0.015 0.    0.    0.    0.    0.    0.   ]
Keyword argument feature is only valid for algorithm `hac`. Given feature `solar+onwind-time` will be ignored.
WARNING:__main__:Keyword argument feature is only valid for algorithm `hac`. Given feature `solar+onwind-time` will be ignored.
WARNING:pyomo.solvers:Could not locate the 'cplex' executable, which is required for solver cplex
ERROR:_helpers:An error happened in module '/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pyomo/opt/solver/shellcmd.py', function 'available': No executable found for solver 'cplex'
Traceback (most recent call last):
  File "/Users/gbotemi/Documents/code/PYPSA/pypsa-earth-versions/pypsa-earth-v0.5/pypsa-earth/.snakemake/scripts/tmp0zvk4oib.cluster_network.py", line 752, in <module>
    clustering = clustering_for_n_clusters(
  File "/Users/gbotemi/Documents/code/PYPSA/pypsa-earth-versions/pypsa-earth-v0.5/pypsa-earth/.snakemake/scripts/tmp0zvk4oib.cluster_network.py", line 592, in clustering_for_n_clusters
    busmap = busmap_for_n_clusters(
  File "/Users/gbotemi/Documents/code/PYPSA/pypsa-earth-versions/pypsa-earth-v0.5/pypsa-earth/.snakemake/scripts/tmp0zvk4oib.cluster_network.py", line 483, in busmap_for_n_clusters
    n_clusters = distribute_clusters(
  File "/Users/gbotemi/Documents/code/PYPSA/pypsa-earth-versions/pypsa-earth-v0.5/pypsa-earth/.snakemake/scripts/tmp0zvk4oib.cluster_network.py", line 375, in distribute_clusters
    results = opt.solve(m)
  File "/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pyomo/opt/base/solvers.py", line 534, in solve
    self.available(exception_flag=True)
  File "/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pyomo/opt/solver/ilmcmd.py", line 35, in available
    if not pyomo.opt.solver.shellcmd.SystemCallSolver.available(
  File "/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pyomo/opt/solver/shellcmd.py", line 140, in available
    raise ApplicationError(msg % self.name)
pyomo.common.errors.ApplicationError: No executable found for solver 'cplex'
[Thu Sep 26 22:37:54 2024]
Error in rule cluster_network:
    jobid: 8
    input: networks/tutorial/elec_s.nc, resources/tutorial/shapes/country_shapes.geojson, resources/tutorial/bus_regions/regions_onshore_elec_s.geojson, resources/tutorial/bus_regions/regions_offshore_elec_s.geojson, resources/tutorial/shapes/gadm_shapes.geojson, data/costs.csv
    output: networks/tutorial/elec_s_6.nc, resources/tutorial/bus_regions/regions_onshore_elec_s_6.geojson, resources/tutorial/bus_regions/regions_offshore_elec_s_6.geojson, resources/tutorial/bus_regions/busmap_elec_s_6.csv, resources/tutorial/bus_regions/linemap_elec_s_6.csv
    log: logs/tutorial/cluster_network/elec_s_6.log (check log file(s) for error details)

RuleException:
CalledProcessError in file /Users/gbotemi/Documents/code/PYPSA/pypsa-earth-versions/pypsa-earth-v0.5/pypsa-earth/Snakefile, line 742:
Command 'set -euo pipefail;  /Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/bin/python3.10 /Users/gbotemi/Documents/code/PYPSA/pypsa-earth-versions/pypsa-earth-v0.5/pypsa-earth/.snakemake/scripts/tmp0zvk4oib.cluster_network.py' returned non-zero exit status 1.
  File "/Users/gbotemi/Documents/code/PYPSA/pypsa-earth-versions/pypsa-earth-v0.5/pypsa-earth/Snakefile", line 742, in __rule_cluster_network
  File "/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/concurrent/futures/thread.py", line 58, in run
```

GLPK
```bash
37 of 39 steps (95%) done
Select jobs to execute...

[Thu Sep 26 23:07:23 2024]
rule solve_sector_network:
    input: data/override_component_attrs, results//prenetworks/elec_s_6_ec_lcopt_Co2L-4H_144H_2030_0.071_AB_10export.nc, data/costs_2030.csv, results//configs/config.yaml
    output: results//postnetworks/elec_s_6_ec_lcopt_Co2L-4H_144H_2030_0.071_AB_10export.nc
    log: results//logs/elec_s_6_ec_lcopt_Co2L-4H_144H_2030_0.071_AB_10export_solver.log, results//logs/elec_s_6_ec_lcopt_Co2L-4H_144H_2030_0.071_AB_10export_python.log, results//logs/elec_s_6_ec_lcopt_Co2L-4H_144H_2030_0.071_AB_10export_memory.log
    jobid: 1
    benchmark: results//benchmarks/solve_network/elec_s_6_ec_lcopt_Co2L-4H_144H_2030_0.071_AB_10export
    reason: Missing output files: results//postnetworks/elec_s_6_ec_lcopt_Co2L-4H_144H_2030_0.071_AB_10export.nc; Input files updated by another job: results//prenetworks/elec_s_6_ec_lcopt_Co2L-4H_144H_2030_0.071_AB_10export.nc
    wildcards: simpl=, clusters=6, ll=copt, opts=Co2L-4H, sopts=144H, planning_horizons=2030, discountrate=0.071, demand=AB, h2export=10
    threads: 8
    resources: tmpdir=/var/folders/c3/657p__892k72qxh6r8fdkqsh0000gn/T, mem_mb=30000, mem_mib=28611

Set parameter WLSAccessID
Set parameter WLSSecret
Set parameter LicenseID to value 2536999
Academic license 2536999 - for non-commercial use only - registered to ka___@gmail.com
/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pulp/apis/gurobi_api.py:170: UserWarning: GUROBI error: Unknown parameter '_test'.
  warnings.warn("GUROBI error: {}.".format(e))
/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pypsa/networkclustering.py:16: UserWarning: The namespace `pypsa.networkclustering` is deprecated and will be removed in PyPSA v0.24. Please use `pypsa.clustering.spatial instead`. 
  warnings.warn(
Demand data folder: data/ssp2-2.6/2030/era5_2013, load path is ['data/ssp2-2.6/2030/era5_2013/Africa.nc'].
Expected files: Africa.nc
Building DAG of jobs...
File path results//prenetworks/elec_s_6_ec_lcopt_Co2L-4H_144H_2030_0.071_AB_10export.nc contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
File path results//configs/config.yaml contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
File path results//postnetworks/elec_s_6_ec_lcopt_Co2L-4H_144H_2030_0.071_AB_10export.nc contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
File path results//benchmarks/solve_network/elec_s_6_ec_lcopt_Co2L-4H_144H_2030_0.071_AB_10export contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
File path results//logs/elec_s_6_ec_lcopt_Co2L-4H_144H_2030_0.071_AB_10export_solver.log contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
File path results//logs/elec_s_6_ec_lcopt_Co2L-4H_144H_2030_0.071_AB_10export_python.log contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
File path results//logs/elec_s_6_ec_lcopt_Co2L-4H_144H_2030_0.071_AB_10export_memory.log contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
File path results//benchmarks/solve_network/elec_s_6_ec_lcopt_Co2L-4H_144H_2030_0.071_AB_10export contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
File path results//logs/elec_s_6_ec_lcopt_Co2L-4H_144H_2030_0.071_AB_10export_solver.log contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
File path results//logs/elec_s_6_ec_lcopt_Co2L-4H_144H_2030_0.071_AB_10export_python.log contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
File path results//logs/elec_s_6_ec_lcopt_Co2L-4H_144H_2030_0.071_AB_10export_memory.log contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
Using shell: /bin/bash
Provided cores: 8
Rules claiming more threads will be scaled down.
Provided resources: mem_mb=30000, mem_mib=28611
Select jobs to execute...
Changing to shadow directory: /Users/gbotemi/Documents/code/PYPSA/pypsa-earth-versions/pypsa-earth-v0.5/pypsa-earth/.snakemake/shadow/tmpjho37svq
/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pypsa/networkclustering.py:16: UserWarning: The namespace `pypsa.networkclustering` is deprecated and will be removed in PyPSA v0.24. Please use `pypsa.clustering.spatial instead`. 
  warnings.warn(
/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pypsa/components.py:318: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attrs.loc[bool_b, "default"] = attrs.loc[bool_b].isin({True, "True"})
/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pypsa/components.py:318: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attrs.loc[bool_b, "default"] = attrs.loc[bool_b].isin({True, "True"})
/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pypsa/components.py:318: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attrs.loc[bool_b, "default"] = attrs.loc[bool_b].isin({True, "True"})
/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pypsa/components.py:318: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attrs.loc[bool_b, "default"] = attrs.loc[bool_b].isin({True, "True"})
INFO:pypsa.io:Imported network elec_s_6_ec_lcopt_Co2L-4H_144H_2030_0.071_AB_10export.nc has buses, carriers, generators, global_constraints, lines, links, loads, storage_units, stores
INFO:pypsa.linopf:Prepare linear problem
/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pypsa/linopf.py:530: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  pd.concat([bus_injection(*arg) for arg in args], axis=1)
/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pypsa/linopf.py:538: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  (-get_as_dense(n, "Load", "p_set", sns) * n.loads.sign)
no h2 export constraint set
INFO:__main__:no h2 export constraint set
INFO:pypsa.linopf:Total preparation time: 1.79s
INFO:pypsa.linopf:Solve linear problem using Glpk solver
ERROR:_helpers:An error happened in module '/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pypsa/linopt.py', function 'run_and_read_glpk': [Errno 2] No such file or directory: '/var/folders/c3/657p__892k72qxh6r8fdkqsh0000gn/T/pypsa-solvedtcfojdr.sol'
Traceback (most recent call last):
  File "/Users/gbotemi/Documents/code/PYPSA/pypsa-earth-versions/pypsa-earth-v0.5/pypsa-earth/.snakemake/shadow/tmpjho37svq/.snakemake/scripts/tmp43nbhh28.solve_network.py", line 1025, in <module>
    n = solve_network(
  File "/Users/gbotemi/Documents/code/PYPSA/pypsa-earth-versions/pypsa-earth-v0.5/pypsa-earth/.snakemake/shadow/tmpjho37svq/.snakemake/scripts/tmp43nbhh28.solve_network.py", line 950, in solve_network
    network_lopf(
  File "/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pypsa/linopf.py", line 1576, in network_lopf
    res = solve(
  File "/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pypsa/linopt.py", line 921, in run_and_read_glpk
    f = open(solution_fn)
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/c3/657p__892k72qxh6r8fdkqsh0000gn/T/pypsa-solvedtcfojdr.sol'
Not cleaning up /Users/gbotemi/Documents/code/PYPSA/pypsa-earth-versions/pypsa-earth-v0.5/pypsa-earth/.snakemake/shadow/tmpjho37svq/.snakemake/scripts/tmp43nbhh28.solve_network.py
[Thu Sep 26 23:07:30 2024]
Error in rule solve_sector_network:
    jobid: 0
    input: data/override_component_attrs, results//prenetworks/elec_s_6_ec_lcopt_Co2L-4H_144H_2030_0.071_AB_10export.nc, data/costs_2030.csv, results//configs/config.yaml
    output: results//postnetworks/elec_s_6_ec_lcopt_Co2L-4H_144H_2030_0.071_AB_10export.nc
    log: results//logs/elec_s_6_ec_lcopt_Co2L-4H_144H_2030_0.071_AB_10export_solver.log, results//logs/elec_s_6_ec_lcopt_Co2L-4H_144H_2030_0.071_AB_10export_python.log, results//logs/elec_s_6_ec_lcopt_Co2L-4H_144H_2030_0.071_AB_10export_memory.log (check log file(s) for error details)

RuleException:
CalledProcessError in file /Users/gbotemi/Documents/code/PYPSA/pypsa-earth-versions/pypsa-earth-v0.5/pypsa-earth/Snakefile, line 1465:
Command 'set -euo pipefail;  /Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/bin/python3.10 /Users/gbotemi/Documents/code/PYPSA/pypsa-earth-versions/pypsa-earth-v0.5/pypsa-earth/.snakemake/shadow/tmpjho37svq/.snakemake/scripts/tmp43nbhh28.solve_network.py' returned non-zero exit status 1.
  File "/Users/gbotemi/Documents/code/PYPSA/pypsa-earth-versions/pypsa-earth-v0.5/pypsa-earth/Snakefile", line 1465, in __rule_solve_sector_network
  File "/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-09-26T230250.632613.snakemake.log
```

**Comment by ekatef** [comment]
Hey @GbotemiB, thanks for reporting!

I suspect, that is `options` line which leads to troubles:

https://github.com/pypsa-meets-earth/pypsa-earth/blob/7ef77254244e22982f4c7ba57b0fd63c7220101f/config.default.yaml#L691-L693

Can you try to comment it out?

**Comment by GbotemiB** [comment]
Hello @katia, 
I figured it out already. It is just as you said. I had to understand the way the config files work. The main config is the `config.default.yaml` file. The parameters for the config weren't set in `config.yaml`, which caused the program to take default from `config.default.yaml` causing the code not to work.

**Comment by ekatef** [comment]
> Hello @Katia, I figured it out already. It is just as you said. I had to understand the way the config files work. The main config is the `config.default.yaml` file. The parameters for the config weren't set in `config.yaml`, which caused the program to take default from `config.default.yaml` causing the code not to work.

Thanks for reporting the issue! My feeling is that it'll be very helpful for folks dealing with similar problems. As a comment, it feels like we may need som additional efforts to make the automated config update more stable and convenient in usage. Let's discuss it in the weekly 🙂
