### ISSUE TITLE
Heat demand missing for US in prepare_sector_network

### ISSUE THREAD

**Issue by GbotemiB** [pz-max/pypsa-africa#1163]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

*Please provide a description of what the bug is and add a minimal example/command for reproducing the bug.*
Heat demand data is missing for US while running the sector model. The errors appears in prepare_sector_network.

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```bash
[Thu Oct 31 21:34:00 2024]
rule prepare_sector_network:
    input: results/US_2021/prenetworks/elec_s_10_ec_lcopt_Co2L-3H_144H_2030_0.071_AB_presec.nc, data/costs_2030.csv, data/hydrogen_salt_cavern_potentials.csv, resources/demand/heat/nodal_energy_heat_totals_AB_s_10_2030.csv, resources/demand/transport_AB_s_10_2030.csv, resources/pattern_profiles/avail_profile_AB_s_10_2030.csv, resources/pattern_profiles/dsm_profile_AB_s_10_2030.csv, resources/demand/nodal_transport_data_AB_s_10_2030.csv, data/override_component_attrs, resources/population_shares/pop_layout_elec_s_10_2030.csv, resources/demand/industrial_energy_demand_per_node_elec_s_10_2030_AB.csv, data/energy_totals_AB_2030.csv, data/airports.csv, data/ports.csv, resources/demand/heat/heat_demand_AB_s_10_2030.csv, resources/demand/heat/ashp_cop_AB_s_10_2030.csv, resources/demand/heat/gshp_cop_AB_s_10_2030.csv, resources/demand/heat/solar_thermal_AB_s_10_2030.csv, resources/demand/heat/district_heat_share_AB_s_10_2030.csv, data/temp_hard_coded/biomass_transport_costs.csv, resources/US_2021/bus_regions/regions_onshore_elec_s_10.geojson, resources/gas_networks/gas_network_elec_s_10.csv
    output: results/US_2021/prenetworks/elec_s_10_ec_lcopt_Co2L-3H_144H_2030_0.071_AB.nc
    jobid: 5
    benchmark: results/US_2021/benchmarks/prepare_network/elec_s_10_ec_lcopt_Co2L-3H_144H_2030_0.071_AB
    reason: Missing output files: results/US_2021/prenetworks/elec_s_10_ec_lcopt_Co2L-3H_144H_2030_0.071_AB.nc
    wildcards: simpl=, clusters=10, ll=copt, opts=Co2L-3H, sopts=144H, planning_horizons=2030, discountrate=0.071, demand=AB
    resources: tmpdir=/var/folders/c3/657p__892k72qxh6r8fdkqsh0000gn/T, mem_mb=2000, mem_mib=1908

/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pypsa/networkclustering.py:16: UserWarning: The namespace `pypsa.networkclustering` is deprecated and will be removed in PyPSA v0.24. Please use `pypsa.clustering.spatial instead`. 
  warnings.warn(
/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pypsa/components.py:318: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attrs.loc[bool_b, "default"] = attrs.loc[bool_b].isin({True, "True"})
/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pypsa/components.py:318: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attrs.loc[bool_b, "default"] = attrs.loc[bool_b].isin({True, "True"})
/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pypsa/components.py:318: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attrs.loc[bool_b, "default"] = attrs.loc[bool_b].isin({True, "True"})
/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pypsa/components.py:318: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attrs.loc[bool_b, "default"] = attrs.loc[bool_b].isin({True, "True"})
INFO:pypsa.io:Imported network elec_s_10_ec_lcopt_Co2L-3H_144H_2030_0.071_AB_presec.nc has buses, carriers, generators, global_constraints, lines, links, loads, storage_units
ERROR:pypsa.io:Error, new components for Generator are not unique
INFO:__main__:adding electricity generation
ERROR:pypsa.io:Error, new components for Link are not unique
INFO:__main__:adding heat
/Users/gbotemi/Documents/code/PYPSA/US/efuels-supply-potentials/submodules/pypsa-earth/.snakemake/scripts/tmpic63ijld.prepare_sector_network.py:2036: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  heat_demand[[sector + " water", sector + " space"]]
/Users/gbotemi/Documents/code/PYPSA/US/efuels-supply-potentials/submodules/pypsa-earth/.snakemake/scripts/tmpic63ijld.prepare_sector_network.py:2036: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  heat_demand[[sector + " water", sector + " space"]]
/Users/gbotemi/Documents/code/PYPSA/US/efuels-supply-potentials/submodules/pypsa-earth/.snakemake/scripts/tmpic63ijld.prepare_sector_network.py:2036: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  heat_demand[[sector + " water", sector + " space"]]
/Users/gbotemi/Documents/code/PYPSA/US/efuels-supply-potentials/submodules/pypsa-earth/.snakemake/scripts/tmpic63ijld.prepare_sector_network.py:2036: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  heat_demand[[sector + " water", sector + " space"]]
/Users/gbotemi/Documents/code/PYPSA/US/efuels-supply-potentials/submodules/pypsa-earth/.snakemake/scripts/tmpic63ijld.prepare_sector_network.py:2044: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  heat_demand.groupby(level=1, axis=1)
INFO:__main__:adding biomass
INFO:__main__:Biomass and Biogas potential fetched from config
INFO:__main__:Biomass potentials spatially resolved equally across all nodes
INFO:__main__:No transport values found for US, using default value of 0.1
INFO:__main__:adding industrial demand
INFO:__main__:adding land transport
INFO:__main__:FCEV share: 0.01
INFO:__main__:EV share: 0.01
INFO:__main__:ICEV share: 0.98
Traceback (most recent call last):
  File "/Users/gbotemi/Documents/code/PYPSA/US/efuels-supply-potentials/submodules/pypsa-earth/.snakemake/scripts/tmpic63ijld.prepare_sector_network.py", line 2869, in <module>
    add_residential(n, costs)
  File "/Users/gbotemi/Documents/code/PYPSA/US/efuels-supply-potentials/submodules/pypsa-earth/.snakemake/scripts/tmpic63ijld.prepare_sector_network.py", line 2511, in add_residential
    heat_shape = heat_shape_raw.rename(
  File "/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pandas/core/frame.py", line 5767, in rename
    return super()._rename(
  File "/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pandas/core/generic.py", line 1115, in _rename
    level = ax._get_level_number(level)
  File "/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 2017, in _get_level_number
    self._validate_index_level(level)
  File "/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 2008, in _validate_index_level
    raise IndexError(
IndexError: Too many levels: Index has only 1 level, not 2
[Thu Oct 31 21:34:46 2024]
Error in rule prepare_sector_network:
    jobid: 5
    input: results/US_2021/prenetworks/elec_s_10_ec_lcopt_Co2L-3H_144H_2030_0.071_AB_presec.nc, data/costs_2030.csv, data/hydrogen_salt_cavern_potentials.csv, resources/demand/heat/nodal_energy_heat_totals_AB_s_10_2030.csv, resources/demand/transport_AB_s_10_2030.csv, resources/pattern_profiles/avail_profile_AB_s_10_2030.csv, resources/pattern_profiles/dsm_profile_AB_s_10_2030.csv, resources/demand/nodal_transport_data_AB_s_10_2030.csv, data/override_component_attrs, resources/population_shares/pop_layout_elec_s_10_2030.csv, resources/demand/industrial_energy_demand_per_node_elec_s_10_2030_AB.csv, data/energy_totals_AB_2030.csv, data/airports.csv, data/ports.csv, resources/demand/heat/heat_demand_AB_s_10_2030.csv, resources/demand/heat/ashp_cop_AB_s_10_2030.csv, resources/demand/heat/gshp_cop_AB_s_10_2030.csv, resources/demand/heat/solar_thermal_AB_s_10_2030.csv, resources/demand/heat/district_heat_share_AB_s_10_2030.csv, data/temp_hard_coded/biomass_transport_costs.csv, resources/US_2021/bus_regions/regions_onshore_elec_s_10.geojson, resources/gas_networks/gas_network_elec_s_10.csv
    output: results/US_2021/prenetworks/elec_s_10_ec_lcopt_Co2L-3H_144H_2030_0.071_AB.nc

RuleException:
CalledProcessError in file /Users/gbotemi/Documents/code/PYPSA/US/efuels-supply-potentials/submodules/pypsa-earth/Snakefile, line 1105:
Command 'set -euo pipefail;  /Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/bin/python3.10 /Users/gbotemi/Documents/code/PYPSA/US/efuels-supply-potentials/submodules/pypsa-earth/.snakemake/scripts/tmpic63ijld.prepare_sector_network.py' returned non-zero exit status 1.
  File "/Users/gbotemi/Documents/code/PYPSA/US/efuels-supply-potentials/submodules/pypsa-earth/Snakefile", line 1105, in __rule_prepare_sector_network
  File "/Users/gbotemi/miniconda3/envs/pypsa-earth-0.4.1/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-10-31T213357.052105.snakemake.log
```

**Comment by GbotemiB** [comment]
This error was traced down to `build_clustered_population_layouts` 
pop_layout is returning nan values
https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/scripts/build_clustered_population_layouts.py#L43
![image](https://github.com/user-attachments/assets/961b2058-b181-4b7e-9895-a0417f830a2b)

**Comment by GbotemiB** [comment]
I have traced part of the issue to `build_clustered_population_layouts`
https://github.com/pypsa-meets-earth/pypsa-earth/blob/8d93ddb30dd4f2e6522cac0864a86996789e69c6/scripts/build_clustered_population_layouts.py#L39

Result from the indicatormatrix returns 0 elements which should not be.
<img width="449" alt="image" src="https://github.com/user-attachments/assets/667bff9a-3729-48d0-8d1f-685f94a60d8e">

Considering NG, results from the indicatormatrix should look like this
<img width="484" alt="image" src="https://github.com/user-attachments/assets/296cdaf4-a676-4742-a6bd-247316a4ede2">

**Comment by ekatef** [comment]
Hello @GbotemiB! Thank you for the detailed description. I wonder if you may be willing to share a solution for this issue? 🙂

**Comment by GbotemiB** [comment]
Hi @ekatef, The issue seems to be from the cutout which i was using previously. I havent test with the cutout for [North America](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/configs/bundle_config.yaml#L261-L269) yet.

**Comment by yerbol-akhmetov** [comment]
hi, @GbotemiB. I think we can close this issue, as the error was solved with new cutouts.

**Comment by GbotemiB** [comment]
Hello @yerbol-akhmetov, thank you. 
Closing now.
