### ISSUE TITLE
GADM server inavailability

### ISSUE THREAD

**Issue by yerbol-akhmetov** [pz-max/pypsa-africa#1247]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

When running `build_shapes` rule `download_GADM` function shows error, because GADM servers are down.

## Error Message

```bash
Traceback (most recent call last):
  File "/home/yerbol/miniconda3/envs/pypsa-earth/lib/python3.10/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
  File "/home/yerbol/miniconda3/envs/pypsa-earth/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/yerbol/miniconda3/envs/pypsa-earth/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yerbol/miniconda3/envs/pypsa-earth/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/home/yerbol/miniconda3/envs/pypsa-earth/lib/python3.10/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/home/yerbol/miniconda3/envs/pypsa-earth/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/home/yerbol/miniconda3/envs/pypsa-earth/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/home/yerbol/miniconda3/envs/pypsa-earth/lib/python3.10/site-packages/urllib3/connection.py", line 693, in connect
    self.sock = sock = self._new_conn()
  File "/home/yerbol/miniconda3/envs/pypsa-earth/lib/python3.10/site-packages/urllib3/connection.py", line 208, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f0b865837c0>, 'Connection to geodata.ucdavis.edu timed out. (connect timeout=300)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yerbol/miniconda3/envs/pypsa-earth/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/yerbol/miniconda3/envs/pypsa-earth/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/home/yerbol/miniconda3/envs/pypsa-earth/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='geodata.ucdavis.edu', port=443): Max retries exceeded with url: /gadm/gadm4.1/gpkg/gadm41_USA.gpkg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0b865837c0>, 'Connection to geodata.ucdavis.edu timed out. (connect timeout=300)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yerbol/PyPSA/efuels-supply-potentials/.snakemake/scripts/tmpg4cqq0s5.build_shapes.py", line 109, in download_GADM
    r = requests.get(GADM_url, stream=True, timeout=300)
  File "/home/yerbol/miniconda3/envs/pypsa-earth/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/yerbol/miniconda3/envs/pypsa-earth/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/yerbol/miniconda3/envs/pypsa-earth/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yerbol/miniconda3/envs/pypsa-earth/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/yerbol/miniconda3/envs/pypsa-earth/lib/python3.10/site-packages/requests/adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='geodata.ucdavis.edu', port=443): Max retries exceeded with url: /gadm/gadm4.1/gpkg/gadm41_USA.gpkg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0b865837c0>, 'Connection to geodata.ucdavis.edu timed out. (connect timeout=300)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yerbol/PyPSA/efuels-supply-potentials/.snakemake/scripts/tmpg4cqq0s5.build_shapes.py", line 1343, in <module>
    country_shapes = countries(
  File "/home/yerbol/PyPSA/efuels-supply-potentials/.snakemake/scripts/tmpg4cqq0s5.build_shapes.py", line 276, in countries
    df_countries = get_GADM_layer(
  File "/home/yerbol/PyPSA/efuels-supply-potentials/.snakemake/scripts/tmpg4cqq0s5.build_shapes.py", line 201, in get_GADM_layer
    file_gpkg, name_file = download_GADM(country_code, update, outlogging)
  File "/home/yerbol/PyPSA/efuels-supply-potentials/.snakemake/scripts/tmpg4cqq0s5.build_shapes.py", line 111, in download_GADM
    raise Exception(
Exception: GADM server is down at https://geodata.ucdavis.edu/gadm/gadm4.1/gpkg/gadm41_USA.gpkg. Data needed for building shapes can't be extracted.
```

**Comment by davide-f** [comment]
Hello @yerbol-akhmetov :D

Thanks for reporting; to solve this problem for the CI, the recent PR https://github.com/pypsa-meets-earth/pypsa-earth/pull/1257 solves the issue: it incorporates some gadm-like file created using geoboundaries as source.

Issue https://github.com/pypsa-meets-earth/pypsa-earth/issues/1258 has also been added to potentially add multiple sources for shapes that may be desirable.
Do you think we can close this issue?

A temporary fix for your case, if you have some copies of the gadm file somewhereelse is to copy the file/folder from a past run into the desired new place

**Comment by yerbol-akhmetov** [comment]
> Hello @yerbol-akhmetov :D
> 
> Thanks for reporting; to solve this problem for the CI, the recent PR #1257 solves the issue: it incorporates some gadm-like file created using geoboundaries as source.
> 
> Issue #1258 has also been added to potentially add multiple sources for shapes that may be desirable. Do you think we can close this issue?
> 
> A temporary fix for your case, if you have some copies of the gadm file somewhereelse is to copy the file/folder from a past run into the desired new place

Thanks, @davide-f. Yes, I think we can close the issue.
