### ISSUE TITLE
Missing arguments in `simplify_network`'s `cluster` and `clustering_for_n_clusters`

### ISSUE THREAD

**Issue by LRydin** [pz-max/pypsa-africa#1268]
## Checklist

- [x] I am using `v0.5.2` and to the best of my knowledge, this issue is valid for `v0.6.0`.
- [X] I am running on a clean [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml), on a linux machine `conda env -f envs/linux-pinned.yaml`.

## Describe the Bug

TL;DR:

 - `arg`s `inputs` and `config` missing on [Lines 609-624](https://github.com/pypsa-meets-earth/pypsa-earth/blob/e3fc578d44d4d2f40b462a10ca96b4f19d2a5296/scripts/simplify_network.py#L609C1-L624C3) and [Lines 651-667](https://github.com/pypsa-meets-earth/pypsa-earth/blob/e3fc578d44d4d2f40b462a10ca96b4f19d2a5296/scripts/simplify_network.py#L651C1-L667C6) in `simplify_network.py`
 - `inputs, outputs, config = snakemake.input, snakemake.output, snakemake.config` missing on [Line 970](https://github.com/pypsa-meets-earth/pypsa-earth/blob/e3fc578d44d4d2f40b462a10ca96b4f19d2a5296/scripts/simplify_network.py#L970) in `simplify_network.py`
 - loose `kwarg` `potential_mode` in  `simplify_network.py` not in `cluster_network.py` (to the best of my knowledge).

# Potential incongruence between `clustering_for_n_clusters` in `simplify_network.py` and `cluster_network.py`.

see [Line 557](https://github.com/pypsa-meets-earth/pypsa-earth/blob/e3fc578d44d4d2f40b462a10ca96b4f19d2a5296/scripts/cluster_network.py#L557) for `clustering_for_n_clusters` in `cluster_network.py`, where we read:

```python
def clustering_for_n_clusters(
    inputs,
    config,
    n,
    n_clusters,
    alternative_clustering,
    gadm_layer_id,
    geo_crs,
    country_list,
    distribution_cluster,
    build_shape_options,
    custom_busmap=False,
    aggregate_carriers=None,
    line_length_factor=1.25,
    aggregation_strategies=dict(),
    solver_name="cbc",
    algorithm="kmeans",
    feature=None,
    extended_link_costs=0,
    focus_weights=None,
):
```

Now note the call in [Line 651](https://github.com/pypsa-meets-earth/pypsa-earth/blob/e3fc578d44d4d2f40b462a10ca96b4f19d2a5296/scripts/simplify_network.py#L651) to `clustering_for_n_clusters` in `simplify_network.py`, which seems to miss two `arg`s (`inputs` and `config`) and includes a `kwarg` `potential_mode` that I cannot trace:

```diff
clustering = clustering_for_n_clusters(
    n,
    n_clusters,
    alternative_clustering,
    gadm_layer_id,
    geo_crs,
    country_list,
    distribution_cluster,
    build_shape_options,
    custom_busmap=False,
    aggregation_strategies=aggregation_strategies,
-    potential_mode=potential_mode,
    solver_name=solver_name,
    algorithm=algorithm,
    feature=feature,
    focus_weights=focus_weights,
)
```

## Potential solution

I believe that:

```python
inputs, outputs, config = snakemake.input, snakemake.output, snakemake.config
```

is needed in `__main__` of `simplify_network.py`, e.g. around [Line 970](https://github.com/pypsa-meets-earth/pypsa-earth/blob/e3fc578d44d4d2f40b462a10ca96b4f19d2a5296/scripts/simplify_network.py#L970). Furthermore, the two `arg`s `inputs` and `config` should be inserted in [Line 609-624](https://github.com/pypsa-meets-earth/pypsa-earth/blob/e3fc578d44d4d2f40b462a10ca96b4f19d2a5296/scripts/simplify_network.py#L609C1-L624C3)

```diff
def cluster(
+    inputs,
+    config,
    n,
    n_clusters,
    alternative_clustering,
    build_shape_options,
    country_list,
    distribution_cluster,
    focus_weights,
    gadm_layer_id,
    geo_crs,
    renewable_config,
    solver_name,
    algorithm="hac",
    feature=None,
    aggregation_strategies=dict(),
):
```

and similarly in [Line 651-667](https://github.com/pypsa-meets-earth/pypsa-earth/blob/e3fc578d44d4d2f40b462a10ca96b4f19d2a5296/scripts/simplify_network.py#L651C1-L667C6), as

```diff
    clustering = clustering_for_n_clusters(
+      inputs,
+      config,
        n,
        n_clusters,
        alternative_clustering,
        gadm_layer_id,
        geo_crs,
        country_list,
        distribution_cluster,
        build_shape_options,
        custom_busmap=False,
        aggregation_strategies=aggregation_strategies,
-        potential_mode=potential_mode,
        solver_name=solver_name,
        algorithm=algorithm,
        feature=feature,
        focus_weights=focus_weights,
    )
```

**Comment by ekatef** [comment]
Hello @LRydin, and thanks a lot for notifying!

I'm right now working on the task which is closely linked with the issue you have traced. Not yet sure exactly what is the matter, and happy to keep you updated.

**Comment by LRydin** [comment]
Hey @ekatef, that's wonderful. I think I will also be trying a few more `simplify` network problems. I have also encountered some elementary issues with the clustering to GAMD with the `alternative_clustering` option. If it helps, I can details my findings here.

**Comment by ekatef** [comment]
> Hey @ekatef, that's wonderful. I think I will also be trying a few more `simplify` network problems. I have also encountered some elementary issues with the clustering to GAMD with the `alternative_clustering` option. If it helps, I can details my findings here.

It would be very much appreciated if you would be interested investigate how alternative clustering work. At the moment, we are aware that there are [some issues ](https://github.com/pypsa-meets-earth/pypsa-earth/labels/alternative_clustering) for sure. A discussion [here](https://github.com/pypsa-meets-earth/pypsa-earth/issues/107) gives some context and lists a possible strategy to improve. Personally, I also expect that some refactoring will be also beneficial (as you have just demonstrated 🙂).

Looking forward for the developments and happy to discuss the results!

**Comment by LRydin** [comment]
Alright, I'm back with some more issues @ekatef . I have been trying to run a system for the Southern African grid including 

```yaml
countries: ['ZA', 'BW', 'CD', 'LS', 'MZ', 'NA', 'MW', 'TZ', 'ZM', 'ZW', 'AO']
```

There are quite a few issues around `cluster_network.py`.

If I try to cluster with `'load'` as the distribution:

```yaml
cluster_options:
  distribute_cluster: ["load"] # Distributes cluster nodes per country according to ['load'],['pop'] or ['gdp']
```

This requires at least `197` clusters, but results in the error:

```shell
INFO:pypsa.io:Imported network elec_s.nc has buses, carriers, generators, lines, links, loads, storage_units
Overwriting marginal_cost of Index(['solar', 'onwind', 'offwind', 'hydro', 'H2', 'electrolysis',
       'fuel cell', 'battery', 'battery inverter'],
      dtype='object') to [0.01  0.015 0.015 0.    0.    0.    0.    0.    0.   ]
INFO:add_electricity:Overwriting marginal_cost of Index(['solar', 'onwind', 'offwind', 'hydro', 'H2', 'electrolysis',
       'fuel cell', 'battery', 'battery inverter'],
      dtype='object') to [0.01  0.015 0.015 0.    0.    0.    0.    0.    0.   ]
Keyword argument feature is only valid for algorithm `hac`. Given feature `solar+onwind-time` will be ignored.
WARNING:__main__:Keyword argument feature is only valid for algorithm `hac`. Given feature `solar+onwind-time` will be ignored.
ERROR:_helpers:An error happened in module '/home/leo/pypsa-earth/scripts/cluster_network.py', function 'distribute_clusters': Country weights L must sum up to 1.0 when distributing clusters. Is 0.0.
Traceback (most recent call last):
  File "/home/leo/pypsa-earth/.snakemake/scripts/tmpqc5kctmb.cluster_network.py", line 759, in <module>
    clustering = clustering_for_n_clusters(
  File "/home/leo/pypsa-earth/.snakemake/scripts/tmpqc5kctmb.cluster_network.py", line 594, in clustering_for_n_clusters
    busmap = busmap_for_n_clusters(
  File "/home/leo/pypsa-earth/.snakemake/scripts/tmpqc5kctmb.cluster_network.py", line 484, in busmap_for_n_clusters
    n_clusters = distribute_clusters(
  File "/home/leo/pypsa-earth/.snakemake/scripts/tmpqc5kctmb.cluster_network.py", line 339, in distribute_clusters
    assert np.isclose(
AssertionError: Country weights L must sum up to 1.0 when distributing clusters. Is 0.0.
```

Similarly, if I run this with `'pop'`

```yaml
cluster_options:
  distribute_cluster: ["pop"] # Distributes cluster nodes per country according to ['load'],['pop'] or ['gdp']
```

The following error occurs:

```shell
INFO:build_shapes:Stage 4 of 5: Starting multiprocessing
Compute population per window:   0%|                                                                    | 0/16 [00:05<?, ? window/s]
ERROR:_helpers:An error happened in module '/home/leo/anaconda3/envs/pypsa-earth/lib/python3.10/site-packages/pandas/core/indexes/base.py', function 'get_loc': 'GADM_ID'
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/leo/anaconda3/envs/pypsa-earth/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'GADM_ID'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/leo/anaconda3/envs/pypsa-earth/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/leo/pypsa-earth/scripts/build_shapes.py", line 751, in process_function_population
    region_geomask, id_mapping = compute_geomask_region(
  File "/home/leo/pypsa-earth/scripts/build_shapes.py", line 871, in compute_geomask_region
    id_to_GADM_ID.append([i + 1, country_rows.iloc[i]["GADM_ID"]])
  File "/home/leo/anaconda3/envs/pypsa-earth/lib/python3.10/site-packages/pandas/core/series.py", line 1121, in __getitem__
    return self._get_value(key)
  File "/home/leo/anaconda3/envs/pypsa-earth/lib/python3.10/site-packages/pandas/core/series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
  File "/home/leo/anaconda3/envs/pypsa-earth/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'GADM_ID'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/leo/pypsa-earth/.snakemake/scripts/tmprogrjq53.cluster_network.py", line 759, in <module>
    clustering = clustering_for_n_clusters(
  File "/home/leo/pypsa-earth/.snakemake/scripts/tmprogrjq53.cluster_network.py", line 594, in clustering_for_n_clusters
    busmap = busmap_for_n_clusters(
  File "/home/leo/pypsa-earth/.snakemake/scripts/tmprogrjq53.cluster_network.py", line 484, in busmap_for_n_clusters
    n_clusters = distribute_clusters(
  File "/home/leo/pypsa-earth/.snakemake/scripts/tmprogrjq53.cluster_network.py", line 277, in distribute_clusters
    add_population_data(
  File "/home/leo/pypsa-earth/scripts/build_shapes.py", line 1218, in add_population_data
    for df_pop_count in pool.imap_unordered(
  File "/home/leo/anaconda3/envs/pypsa-earth/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
  File "/home/leo/anaconda3/envs/pypsa-earth/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/leo/pypsa-earth/scripts/build_shapes.py", line 751, in process_function_population
    region_geomask, id_mapping = compute_geomask_region(
  File "/home/leo/pypsa-earth/scripts/build_shapes.py", line 871, in compute_geomask_region
    id_to_GADM_ID.append([i + 1, country_rows.iloc[i]["GADM_ID"]])
  File "/home/leo/anaconda3/envs/pypsa-earth/lib/python3.10/site-packages/pandas/core/series.py", line 1121, in __getitem__
    return self._get_value(key)
  File "/home/leo/anaconda3/envs/pypsa-earth/lib/python3.10/site-packages/pandas/core/series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
  File "/home/leo/anaconda3/envs/pypsa-earth/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'GADM_ID'
```

And if I run this with `'gdp'`

```yaml
cluster_options:
  distribute_cluster: ["gdp"] # Distributes cluster nodes per country according to ['load'],['pop'] or ['gdp']
```

The following error occurs:

```shell
  connectivity, n_connected_components = _fix_connectivity(
ERROR:_helpers:An error happened in module '/home/leo/anaconda3/envs/pypsa-earth/lib/python3.10/site-packages/pypsa/clustering/spatial.py', function 'consense': In Line cluster country, the values of attribute country do not agree:
Line
175    ZM
176    ZM
177    ZM
192    ZW
Name: country, dtype: object
Traceback (most recent call last):
  File "/home/leo/pypsa-earth/.snakemake/scripts/tmpl05ln6gi.cluster_network.py", line 759, in <module>
    clustering = clustering_for_n_clusters(
  File "/home/leo/pypsa-earth/.snakemake/scripts/tmpl05ln6gi.cluster_network.py", line 609, in clustering_for_n_clusters
    clustering = get_clustering_from_busmap(
  File "/home/leo/anaconda3/envs/pypsa-earth/lib/python3.10/site-packages/pypsa/clustering/spatial.py", line 473, in get_clustering_from_busmap
    lines, lines_t, linemap = aggregatelines(
  File "/home/leo/anaconda3/envs/pypsa-earth/lib/python3.10/site-packages/pypsa/clustering/spatial.py", line 416, in aggregatelines
    df = df.groupby(grouper).agg(static_strategies)
  File "/home/leo/anaconda3/envs/pypsa-earth/lib/python3.10/site-packages/pandas/core/groupby/generic.py", line 1432, in aggregate
    result = op.agg()
  File "/home/leo/anaconda3/envs/pypsa-earth/lib/python3.10/site-packages/pandas/core/apply.py", line 190, in agg
    return self.agg_dict_like()
  File "/home/leo/anaconda3/envs/pypsa-earth/lib/python3.10/site-packages/pandas/core/apply.py", line 423, in agg_dict_like
    return self.agg_or_apply_dict_like(op_name="agg")
  File "/home/leo/anaconda3/envs/pypsa-earth/lib/python3.10/site-packages/pandas/core/apply.py", line 1608, in agg_or_apply_dict_like
    result_index, result_data = self.compute_dict_like(
  File "/home/leo/anaconda3/envs/pypsa-earth/lib/python3.10/site-packages/pandas/core/apply.py", line 496, in compute_dict_like
    results = [
  File "/home/leo/anaconda3/envs/pypsa-earth/lib/python3.10/site-packages/pandas/core/apply.py", line 497, in <listcomp>
    getattr(obj._gotitem(key, ndim=1), op_name)(how, **kwargs)
  File "/home/leo/anaconda3/envs/pypsa-earth/lib/python3.10/site-packages/pandas/core/groupby/generic.py", line 294, in aggregate
    return self._python_agg_general(func, *args, **kwargs)
  File "/home/leo/anaconda3/envs/pypsa-earth/lib/python3.10/site-packages/pandas/core/groupby/generic.py", line 327, in _python_agg_general
    result = self._grouper.agg_series(obj, f)
  File "/home/leo/anaconda3/envs/pypsa-earth/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 864, in agg_series
    result = self._aggregate_series_pure_python(obj, func)
  File "/home/leo/anaconda3/envs/pypsa-earth/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 885, in _aggregate_series_pure_python
    res = func(group)
  File "/home/leo/anaconda3/envs/pypsa-earth/lib/python3.10/site-packages/pandas/core/groupby/generic.py", line 324, in <lambda>
    f = lambda x: func(x, *args, **kwargs)
  File "/home/leo/anaconda3/envs/pypsa-earth/lib/python3.10/site-packages/pypsa/clustering/spatial.py", line 135, in consense
    assert (x == v).all() or x.isnull().all(), (
AssertionError: In Line cluster country, the values of attribute country do not agree:
Line
175    ZM
176    ZM
177    ZM
192    ZW
Name: country, dtype: object
```

which means, at this stage, I cannot cluster this network. I have tried building the shapes `build_shapes` with both `"standard"` and `"api"`.

```yaml
build_shape_options:
  gadm_layer_id: 2 # GADM level area used for the gadm_shapes. Codes are country-dependent but roughly: 0: country, 1: 
  ...
  worldpop_method: "standard" # "standard" pulls from web 1kmx1km raster, "api" pulls from API 100mx100m raster,
```

and

```yaml
build_shape_options:
  gadm_layer_id: 2 # GADM level area used for the gadm_shapes. Codes are country-dependent but roughly: 0: country, 1: 
  ...
  worldpop_method: "api" # "standard" pulls from web 1kmx1km raster, "api" pulls from API 100mx100m raster,
```

**Comment by davide-f** [comment]
Hello :)
This issue looks to have been solved, is it still an issue?
