### ISSUE TITLE
Error in snakemake

### ISSUE THREAD

**Issue by hazemakhalek** [pz-max/pypsa-africa#475]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate. Latest release
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug
I only face this issue with the new pypsa-earth environment. It doesn't happen with the old pypsa-africa env

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```bash
Building DAG of jobs...
WARNING:snakemake.logging:Building DAG of jobs...
Using shell: /usr/bin/bash
WARNING:snakemake.logging:Using shell: /usr/bin/bash
Provided cores: 25
WARNING:snakemake.logging:Provided cores: 25
Rules claiming more threads will be scaled down.
WARNING:snakemake.logging:Rules claiming more threads will be scaled down.
Traceback (most recent call last):
  File "/home/haz43975/anaconda3/envs/pypsa-earth/lib/python3.9/site-packages/snakemake/__init__.py", line 733, in snakemake
    success = workflow.execute(
  File "/home/haz43975/anaconda3/envs/pypsa-earth/lib/python3.9/site-packages/snakemake/workflow.py", line 1031, in execute
    logger.run_info("\n".join(dag.stats()))
  File "/home/haz43975/anaconda3/envs/pypsa-earth/lib/python3.9/site-packages/snakemake/dag.py", line 2415, in stats
    yield tabulate(rows, headers="keys")
  File "/home/haz43975/anaconda3/envs/pypsa-earth/lib/python3.9/site-packages/tabulate/__init__.py", line 2048, in tabulate
    list_of_lists, headers = _normalize_tabular_data(
  File "/home/haz43975/anaconda3/envs/pypsa-earth/lib/python3.9/site-packages/tabulate/__init__.py", line 1471, in _normalize_tabular_data
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/home/haz43975/anaconda3/envs/pypsa-earth/lib/python3.9/site-packages/tabulate/__init__.py", line 1471, in <lambda>
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/home/haz43975/anaconda3/envs/pypsa-earth/lib/python3.9/site-packages/tabulate/__init__.py", line 107, in _is_separating_line
    (len(row) >= 1 and row[0] == SEPARATING_LINE)
  File "/home/haz43975/anaconda3/envs/pypsa-earth/lib/python3.9/site-packages/snakemake/rules.py", line 1222, in __eq__
    return self.name == other.name and self.output == other.output
AttributeError: 'str' object has no attribute 'name'
```

**Comment by pz-max** [comment]
Thanks @Hazem-IEG for reporting. Did you execute `snakemake -j1 solve_all_networks` or how can I reproduce the error?
Looks to me that we maybe have to reduce the snakemake version.

**Comment by hazemakhalek** [comment]
@pz-max Yes this is the command I executed

**Comment by pz-max** [comment]
> @pz-max Yes this is the command I executed

Perfect. I will wait until tomorrow when the CI should be able to work again (GADM is planned to go back online)

**Comment by pz-max** [comment]
Bug is gone. Was related to the availability to GADM shapes
