### ISSUE TITLE
Error in simplify_network due to misinterpretation of links

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#586]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

When running the workflow branch [create_statistics](https://github.com/pypsa-meets-earth/pypsa-earth/pull/579) for China, an error on simplify_network appears that needs to be addressed.

This issue requires:
- investigating and fixing simplify_links as needed; could be worth to compare the script with the pypsa-eur developments to see if we missed something
- it would be worth investigating the effects of simplify_links with option hvdc_as_lines = true

## Error Message

```bash
Traceback (most recent call last):
  File "/data/davidef/git_world/pypsa-earth/.snakemake/scripts/tmp14nyount.simplify_network.py", line 532, in <module>
    n, simplify_links_map = simplify_links(
  File "/data/davidef/git_world/pypsa-earth/.snakemake/scripts/tmp14nyount.simplify_network.py", line 346, in simplify_links
    lengths = n.links.loc[all_links, "length"]
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/indexing.py", line 1067, in __getitem__
    return self._getitem_tuple(key)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/indexing.py", line 1247, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/indexing.py", line 991, in _getitem_lowerdim
    return getattr(section, self.name)[new_key]
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/indexing.py", line 1073, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/indexing.py", line 1301, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/indexing.py", line 1239, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/indexing.py", line 1432, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 6070, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 6133, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['1026801049-1_0', '1026801057-1_0'] not in index"
```

**Comment by ekatef** [comment]
@davide-f, thanks a lot for the posting! We had such issue when working on a model for China but it was not obvious how to reproduce it. The `line_id` in the old and in the new cases differ but generally the issue looks the same. So, probably results of our old investigation could be helpful.

The troubles we caused by a specific topology of a grid part connecting the AC and DC grids:

<img width="550" alt="image" src="https://user-images.githubusercontent.com/30229437/216111776-3e61e8e4-f487-457c-ac3d-371c245540ac.png">

blue = AC 500kV 
magenta = DC 800 kV 
red = AC 1000 kV

Both ends of the highlighted AC line are connected with the DC grid (via converters which are visible with some zooming). For some reasons that leads to inclusion of this AC line into analysis to as one of the connecting components of a DC-adjacency_matrix. After that an algorithm of `simplify_links` tries to locate this line looking into a list of the DC lines and obviously fails with the KeyError.

**Comment by davide-f** [comment]
Nice description! really handy for who will be willing to tackle this issue :D
