### ISSUE TITLE
Non managed expection when clean_substations.geojson is empty

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#642]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

We don't manage the exeption when all_clean_substations.geojson is empty.
This may be revised and add a custom error message.
Indeed, when no clean_substations are available after cleaning it means that:
- when lines are available, then the option add line endings may be disabled and a prompt message should recommend to do so.
- Alternatively, if really no substations (and lines) are available, then pypsa-earth has nothing to optimize so the error may be understandable. A message should suggest to add manually nodes, such as using the future linkers

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```bash
Traceback (most recent call last):
  File "/data/davidef/git_world/pypsa-earth/.snakemake/scripts/tmppbxf587l.build_osm_network.py", line 858, in <module>
    built_network(
  File "/data/davidef/git_world/pypsa-earth/.snakemake/scripts/tmppbxf587l.build_osm_network.py", line 730, in built_network
    buses = gpd.read_file(inputs["substations"])
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/geopandas/io/file.py", line 259, in _read_file
    return _read_file_fiona(
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/geopandas/io/file.py", line 303, in _read_file_fiona
    with reader(path_or_bytes, **kwargs) as features:
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/fiona/env.py", line 457, in wrapper
    return f(*args, **kwds)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/fiona/__init__.py", line 335, in open
    colxn = Collection(
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/fiona/collection.py", line 234, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 587, in fiona.ogrext.Session.start
  File "fiona/ogrext.pyx", line 143, in fiona.ogrext.gdal_open_vector
fiona.errors.DriverError: 'resources/GM/osm/clean/all_clean_substations.geojson' not recognized as a supported file format.
```

**Comment by ekatef** [comment]
@davide-f, do you have any hints on how to reproduce it? :)

**Comment by davide-f** [comment]
The most likely way to debug these problems is to test "FK".
FYI: FK is not an UN country but it has its own 2country letter and it is related to a region with no data at all in OSM nor it is recognized as a region in geofabrik.
This "country code" should trigger all geojson-related problems related to OSM

As a comment: in dowload_osm_data, it is expected that earth_osm creates the files; however, when no data are found, the files are not created and that triggers error during the [moving phase in download_osm_data](https://github.com/pypsa-meets-earth/pypsa-earth/blob/6a8871dafcc844703123377520669578999b86f1/scripts/download_osm_data.py#L126-L140)

In this block, we shall add a check to see if the input file exists.
If it does not, then an empty file shall be created instead in the final corresponding output.

**Comment by ekatef** [comment]
@davide-f, thanks a lot for explanations! 

I'm able to reproduce an error for Falkland Islands with slightly different details. Rather `build_shapes` and `download_osm_data` are complaining. However, my feeling is that you have explained the reason of the troubles very clearly, and it should be not very complicated to reproduce relevant errors when working on this issue.

The approach you have described looks logical and I think also will be very handy for who will tackle it :)

**Comment by ekatef** [comment]
For the sake of completeness, there are error listing I obtain when testing on "FK":

* `build_shapes`
```bash
File "~/_github_/pypsa-earth/.snakemake/scripts/tmpml50b1w1.build_shapes.py", line 929, in <module>
    gadm_shapes = gadm(
  File "~/_github_/pypsa-earth/.snakemake/scripts/tmpml50b1w1.build_shapes.py", line 869, in gadm
    .apply(lambda id: three_2_two_digits_country(id[0]) + "." + id[1])
  File "~/opt/miniconda3/envs/pypsa-earth-upd5/lib/python3.10/site-packages/pandas/core/series.py", line 4771, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "~/opt/miniconda3/envs/pypsa-earth-upd5/lib/python3.10/site-packages/pandas/core/apply.py", line 1123, in apply
    return self.apply_standard()
  File "~/opt/miniconda3/envs/pypsa-earth-upd5/lib/python3.10/site-packages/pandas/core/apply.py", line 1174, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2924, in pandas._libs.lib.map_infer
  File "~/_github_/pypsa-earth/.snakemake/scripts/tmpml50b1w1.build_shapes.py", line 869, in <lambda>
    .apply(lambda id: three_2_two_digits_country(id[0]) + "." + id[1])
IndexError: list index out of range
``` 
* `download_osm_data`

```bash
INFO:snakemake.logging:
ERROR:osm_data_extractor:FK not found. check view_region()
Traceback (most recent call last):
  File "~/Documents/_github_/pypsa-earth/.snakemake/scripts/tmpiblveq9h.download_osm_data.py", line 112, in <module>
    eo.get_osm_data(
  File "~/opt/miniconda3/envs/pypsa-earth-upd5/lib/python3.10/site-packages/earth_osm/eo.py", line 97, in get_osm_data
    region_tuple_list = [get_region_tuple(rs) for rs in region_list]
  File "~/opt/miniconda3/envs/pypsa-earth-upd5/lib/python3.10/site-packages/earth_osm/eo.py", line 97, in <listcomp>
    region_tuple_list = [get_region_tuple(rs) for rs in region_list]
  File "~/opt/miniconda3/envs/pypsa-earth-upd5/lib/python3.10/site-packages/earth_osm/gfk_data.py", line 172, in get_region_tuple
    id = get_id_by_str(region_str)
  File "~/opt/miniconda3/envs/pypsa-earth-upd5/lib/python3.10/site-packages/earth_osm/gfk_data.py", line 161, in get_id_by_str
    raise KeyError(f'{region_str} not found. check view_region()')
KeyError: 'FK not found. check view_region()'
```
