### ISSUE TITLE
KeyError in simplify_network when to_substations simplification flag is on

### ISSUE THREAD

**Issue by ekatef** [pz-max/pypsa-africa#646]
Current implementations of `aggregate_to_substations` and `merge_isolated_nodes` lead to some troubles  if `to_substations: true` set in `config.yaml`. Namely, run of `simplify_network` terminates with `KeyError(f"Column not found: {key}")`.

## Checklist

- [X] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [X] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

Setting `to_substations: true` set in `config.yaml` leads to execution of `aggregate_to_substations()` which results in dropping of `bus_id` column in `n.buses` dataframe. (The direct drop reason is [aggregatebuses()](https://github.com/PyPSA/PyPSA/blob/acf8584457b124391ebf45f417e5ab1e37e1d289/pypsa/networkclustering.py#L207))  

That causes further a KeyError when trying as use `bus_id` column when merging isolated nodes:

https://github.com/pypsa-meets-earth/pypsa-earth/blob/1f08e834774745f1d209cbf9ea07556c9bb305cc/scripts/simplify_network.py#L656-L657

## Error Message

```bash
INFO:__main__:Aggregating buses that are no substations or have no valid offshore connection
~/pypsa-earth/.snakemake/scripts/tmp69a_7th2.simplify_network.py:474: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  busmap.loc[buses_i] = dist.idxmin(1)
~/opt/miniconda3/envs/pypsa-earth-upd5/lib/python3.10/site-packages/cartopy/mpl/style.py:76: UserWarning: facecolor will have no effect as it has been defined as "never".
  warnings.warn('facecolor will have no effect as it has been '
~/opt/miniconda3/envs/pypsa-earth-upd5/lib/python3.10/site-packages/cartopy/mpl/style.py:76: UserWarning: facecolor will have no effect as it has been defined as "never".
  warnings.warn('facecolor will have no effect as it has been '
Traceback (most recent call last):
  File "~/pypsa-earth/.snakemake/scripts/tmp69a_7th2.simplify_network.py", line 842, in <module>
    n, merged_nodes_map = merge_isolated_nodes(
  File "~/pypsa-earth/.snakemake/scripts/tmp69a_7th2.simplify_network.py", line 685, in merge_isolated_nodes
    n.buses.loc[i_suffic_load].groupby("country")["bus_id"].first().to_dict()
  File "~/opt/miniconda3/envs/pypsa-earth-upd5/lib/python3.10/site-packages/pandas/core/groupby/generic.py", line 1416, in __getitem__
    return super().__getitem__(key)
  File "~/opt/miniconda3/envs/pypsa-earth-upd5/lib/python3.10/site-packages/pandas/core/base.py", line 248, in __getitem__
    raise KeyError(f"Column not found: {key}")
KeyError: 'Column not found: bus_id'
```

**Comment by ekatef** [comment]
An obvious solution would be to avoid referring `bus_id` in `simplify_network`. However, I'm not sure if dropping `bus_id` is an intended effect of aggregation. Probably, that is this column loss which should be fixed as it feels natural to have the model data structure invariant in regard to the particular workflow path

**Comment by ekatef** [comment]
Interestingly, the error message looks differently in the updated environment version:

```bash
Traceback (most recent call last):
  File "~/pypsa-earth/.snakemake/scripts/tmpbvq3wl07.simplify_network.py", line 756, in <module>
    n, substation_map = aggregate_to_substations(n, aggregation_strategies)
  File "~/pypsa-earth/.snakemake/scripts/tmpbvq3wl07.simplify_network.py", line 478, in aggregate_to_substations
    busmap.loc[buses_i] = dist.idxmin(1)
  File "~/miniconda3/envs/pypsa-earth-upd6/lib/python3.10/site-packages/pandas/core/frame.py", line 10610, in idxmin
    res = data._reduce(
  File "~/miniconda3/envs/pypsa-earth-upd6/lib/python3.10/site-packages/pandas/core/frame.py", line 10504, in _reduce
    result = df._reduce(
  File "~/miniconda3/envs/pypsa-earth-upd6/lib/python3.10/site-packages/pandas/core/frame.py", line 10519, in _reduce
    res = df._mgr.reduce(blk_func)
  File "~/miniconda3/envs/pypsa-earth-upd6/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 1534, in reduce
    nbs = blk.reduce(func)
  File "~/miniconda3/envs/pypsa-earth-upd6/lib/python3.10/site-packages/pandas/core/internals/blocks.py", line 339, in reduce
    result = func(self.values)
  File "~/miniconda3/envs/pypsa-earth-upd6/lib/python3.10/site-packages/pandas/core/frame.py", line 10482, in blk_func
    return op(values, axis=axis, skipna=skipna, **kwds)
  File "~/miniconda3/envs/pypsa-earth-upd6/lib/python3.10/site-packages/pandas/core/nanops.py", line 96, in _f
    return f(*args, **kwargs)
  File "~/miniconda3/envs/pypsa-earth-upd6/lib/python3.10/site-packages/pandas/core/nanops.py", line 1193, in nanargmin
    result = values.argmin(axis)  # type: ignore[var-annotated]
ValueError: attempt to get argmin of an empty sequence
``` 

I suspect that might be linked with the updated `pandas` version

**Comment by ekatef** [comment]
The current error seems to be in fact connected with `pandas` update and triggered by an empty `buses_i` list. Previously that has been a warning `FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning`

**Comment by ekatef** [comment]
The reason of the initial issue with `Column not found: {key}` is a discrepancy between naming conventions of `PyPSA::get_clustering_from_busmap( )` and local `merge_isolated_nodes( )`. In particular, in `aggregatebuses( )` [there lines](https://github.com/PyPSA/PyPSA/blob/30214e7a7ac3b204987c7479f44f94db53b7710f/pypsa/networkclustering.py#L207-L210) lead to a drop of `bus_id` column, while indexing with `"bus_id"` is used in `merge_isolated_nodes` :

https://github.com/pypsa-meets-earth/pypsa-earth/blob/bf3cbead03f9f95079e0ad09df1dbab85ce66112/scripts/simplify_network.py#L659-L662

In case the network has been obtained before merging by `get_clustering_from_busmap( )`, as it's the case when `to_substations: true`, indexing n.buses with `bus_id` causes a key error
