### ISSUE TITLE
Simplify_links problem when running PyPSA-Earth to simulate EU

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#703]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

When running PyPSA-Earth to simulate the european network, the simplify_link procedure in simplify_network may lead to problems.
To reproduce, the country list is: `countries: [AL, AT, BA, BE, BG, CH, CZ, DE, DK, EE, ES, FI, FR, GB, GR, HR, HU, IE, IT, LT, LU, LV, ME, MK, NL, "NO", PL, PT, RO, RS, SE, SI, SK]`

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```bash
INFO:__main__:Simplifying connected link components
INFO:__main__:Joining the links 61910377-1_0, convert_3552_6527 connecting the buses 1550, 6527, 6530 to simple link 61910377-1_0+1
INFO:__main__:Joining the links 203657876-1_0, convert_20309_26561 connecting the buses 1550, 26561, 26560 to simple link 203657876-1_0+1
INFO:__main__:Joining the links convert_2665_5069, 559730321-1_0, 559730320-1_0, 559725696-1_0 connecting the buses 5071, 5069, 26572, 26571, 26563 to simple link 559725696-1_0+3
INFO:__main__:Joining the links convert_2665_5072, 559751653-1_0 connecting the buses 5071, 5072, 1556 to simple link 559751653-1_0+1
INFO:__main__:Joining the links convert_3552_6529, 203672472-1_0, convert_20309_26562 connecting the buses 6530, 6529, 26562, 26560 to simple link 203672472-1_0+2
INFO:__main__:Joining the links 810410262-1_0, 810410262-2_0, 559751662-1_0, convert_787_1554 connecting the buses 26563, 26404, 1554, 1555 to simple link 810410262-1_0+2
INFO:__main__:Joining the links 216499899-1_0, convert_1555_3048 connecting the buses 9873, 3048, 3049 to simple link 216499899-1_0+1
INFO:__main__:Joining the links 216499899-2_0, convert_1555_3047 connecting the buses 9872, 3047, 3049 to simple link 216499899-2_0+1
INFO:__main__:Joining the links 98356251-1_0, 129709279-1_0, 1023443703-1_0 connecting the buses 6404, 9692, 26241, 26198 to simple link 98356251-1_0+2
INFO:__main__:Joining the links 98356251-2_0, 129709279-2_0, 1023443703-2_0 connecting the buses 6403, 9691, 26240, 26197 to simple link 98356251-2_0+2
INFO:__main__:Joining the links convert_13123_18301, 140477917-2_0, 36939840-2_0, 136796521-1_0, 136796521-2_0, convert_1314_2562 connecting the buses 18300, 18301, 18481, 18297, 2562, 2561 to simple link 136796521-1_0+4
INFO:__main__:Joining the links convert_13123_18302, 140477917-1_0, 36939840-1_0, 185107614-1_0, 185107614-2_0 connecting the buses 18300, 18302, 18482, 18298, 2563 to simple link 185107614-1_0+3
INFO:__main__:Joining the links convert_12219_17187, 394245336-1_0 connecting the buses 17186, 17187, 17520 to simple link 394245336-1_0+1
INFO:__main__:Joining the links convert_13930_19236, 575816471-2_0 connecting the buses 19239, 19236, 19202 to simple link 575816471-2_0+1
INFO:__main__:Joining the links convert_13930_19238, 575816471-1_0 connecting the buses 19239, 19238, 19203 to simple link 575816471-1_0+1
INFO:__main__:Joining the links convert_13930_19240, 575816468-1_0, convert_20172_26416 connecting the buses 19239, 19240, 26416, 26415 to simple link 575816468-1_0+2
INFO:__main__:Joining the links 97755055-1_0, convert_5640_9638 connecting the buses 9643, 9638, 9639 to simple link 97755055-1_0+1
INFO:__main__:Joining the links convert_5641_9644, 297522703-1_0, convert_5640_9640 connecting the buses 9641, 9644, 9640, 9639 to simple link 297522703-1_0+2
INFO:__main__:Joining the links convert_5640_9637, 97755055-2_0 connecting the buses 9639, 9637, 9642 to simple link 97755055-2_0+1
INFO:__main__:Joining the links 669014489-1_0, 669014489-2_0, 849010781-1_0, 849010781-2_0, convert_2025_3903 connecting the buses 3408, 26276, 3903, 3902 to simple link 669014489-2_0+2
INFO:__main__:Joining the links convert_1383_2728, 920251843-1_0 connecting the buses 2729, 2728, 22527 to simple link 920251843-1_0+1
INFO:__main__:Joining the links convert_9573_14144, 129927639-1_0, 257781200-1_0, 257781203-1_0, 257781200-2_0, 257781203-2_0, 137729287-1_1 connecting the buses 14146, 14144, 14337, 21837, 21803 to simple link 137729287-1_1+3
INFO:__main__:Joining the links convert_1926_3726, 244859552-1_0 connecting the buses 3727, 3726, 3720 to simple link 244859552-1_0+1
INFO:__main__:Joining the links convert_4487_8047, 304620091-1_0, 304620091-2_0, convert_248_478 connecting the buses 8046, 8047, 478, 476 to simple link 304620091-2_0+2
INFO:__main__:Joining the links 509435793-1_0, 326306362-1_0, 161371062-1_0, 161371062-2_0, convert_248_477 connecting the buses 15614, 26286, 26284, 477, 476 to simple link 161371062-1_0+3
INFO:__main__:Joining the links 895083673-1_0, convert_4258_7639 connecting the buses 15614, 7639, 7638 to simple link 895083673-1_0+1
INFO:__main__:Joining the links 493642079-1_0, convert_12372_17374 connecting the buses 6387, 17374, 17375 to simple link 493642079-1_0+1
INFO:__main__:Joining the links convert_12531_17583, 274678246-1_0 connecting the buses 17584, 17583, 17899 to simple link 274678246-1_0+1
INFO:__main__:Joining the links convert_11574_16435, 568527667-1_0, 568527667-1_1, 567187365-1_0 connecting the buses 16434, 16435, 26370, 28687, 26330 to simple link 567187365-1_0+3
Traceback (most recent call last):
  File "/data/davidef/git_world/pypsa-earth/.snakemake/scripts/tmpsa8gwpo0.simplify_network.py", line 734, in <module>
    n, simplify_links_map = simplify_links(
  File "/data/davidef/git_world/pypsa-earth/.snakemake/scripts/tmpsa8gwpo0.simplify_network.py", line 343, in simplify_links
    lengths = n.links.loc[all_links, "length"]
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/indexing.py", line 1097, in __getitem__
    return self._getitem_tuple(key)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/indexing.py", line 1280, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/indexing.py", line 1024, in _getitem_lowerdim
    return getattr(section, self.name)[new_key]
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/indexing.py", line 1332, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/indexing.py", line 1272, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/indexing.py", line 1462, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5876, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5938, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['690326581-1_0'] not in index"
```

**Comment by davide-f** [comment]
Issue linked to #621

**Comment by davide-f** [comment]
Similar issue appears with philippines (PH) and japan (JP)
Reproducible using the PR https://github.com/pypsa-meets-earth/pypsa-earth/pull/701 using default configuration (5 clusters, though it is not relevant for this issue).
@ekatef this may be interesting for what we discussed today. PH shouldn't be too big to simulate

``` bash
Traceback (most recent call last):
  File "/data/davidef/git_world/pypsa-earth/.snakemake/scripts/tmpaxdk9_eb.simplify_network.py", line 743, in <module>
    n, simplify_links_map = simplify_links(
  File "/data/davidef/git_world/pypsa-earth/.snakemake/scripts/tmpaxdk9_eb.simplify_network.py", line 347, in simplify_links
    lengths = n.links.loc[all_links, "length"]
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/indexing.py", line 1097, in __getitem__
    return self._getitem_tuple(key)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/indexing.py", line 1280, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/indexing.py", line 1024, in _getitem_lowerdim
    return getattr(section, self.name)[new_key]
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/indexing.py", line 1332, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/indexing.py", line 1272, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/indexing.py", line 1462, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5876, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5938, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['1119999463-1_0'] not in index"
```

**Comment by davide-f** [comment]
The problem for PH disappears when using xarray v2023!
That sounds really misterious

**Comment by davide-f** [comment]
Closing for now
