### ISSUE TITLE
Unexpected behaviour in clustering for Lithuania

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#735]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

When using PR #701 , an error appears for Lithuania.
During the clustering, for some reason the only link that is placed in Lithuania gets clustered into the same node and loses the bus0 and bus1 tags. Moreover, the build_year tag becomes nan and that triggers the error denoted in:
https://github.com/PyPSA/PyPSA/issues/637

This issue needs investigation.

To replicate, please use #701 using default configuration on countries: ["LT"] and clusters: [5]

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```bash
Traceback (most recent call last):
  File "/data/davidef/git_world/pypsa-earth/.snakemake/scripts/tmp9bknsrmp.add_extra_components.py", line 242, in <module>
    n = pypsa.Network(snakemake.input.network)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pypsa/components.py", line 341, in __init__
    self.import_from_netcdf(import_name)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pypsa/io.py", line 644, in import_from_netcdf
    _import_from_importer(network, importer, basename=basename, skip_time=skip_time)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pypsa/io.py", line 794, in _import_from_importer
    import_components_from_dataframe(network, df, component)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pypsa/io.py", line 860, in import_components_from_dataframe
    dataframe[k] = dataframe[k].astype(static_attrs.at[k, "typ"])
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/generic.py", line 6324, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 451, in astype
    return self.apply(
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 352, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 511, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 242, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 187, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 105, in _astype_nansafe
    return _astype_float_to_int_nansafe(arr, dtype, copy)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 150, in _astype_float_to_int_nansafe
    raise IntCastingNaNError(
pandas.errors.IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer
```

**Comment by davide-f** [comment]
@ekatef this problem still applies for LT but it is not related to simplify_links or at least not directly. It occurs in the clustering most likely because the 2 nodes of a link get clustered together maybe and the component doesn't get removed for some reason I think.

Could be nice to check if there have been developments on the cluster_network side in pypsa-eur, it seems there may be some

**Comment by davide-f** [comment]
I think I found a solution and pushed into my open PR
