### ISSUE TITLE
Revise augmentation procedure for networks with HVDC part

### ISSUE THREAD

**Issue by ekatef** [pz-max/pypsa-africa#765]
Currently there are some troubles when building augmented network for a network which contain DC lines. 

## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [ ] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

Namely, when calculating an underwater_fraction for links shapely error is thrown by an attempt to call loads on link geometries:

https://github.com/pypsa-meets-earth/pypsa-earth/blob/b015ab2883dfc2178c2ee3aa12ac486b6cb9abeb/scripts/base_network.py#L157

It seems to be linked with a fact that lines geometry is not restored when [processing links](https://github.com/pypsa-meets-earth/pypsa-earth/blob/b015ab2883dfc2178c2ee3aa12ac486b6cb9abeb/scripts/simplify_network.py#L362-L379) in `simplify_network` which leads to NaN/empty string geometries for some links.

A possible way to fix links geometries would be to add `geometry` column. An attempt was done in #768 but has not been successful due to consequent troubles with network export to netcdf. Another approach is needed like `import_components_from_dataframe` used in `base_network`.

**Way to reproduce**: run a workflow for CD with `add_to_snakefile: true` for `augmented_line_connection` and `hvdc_as_lines: false`.

## Error Message

```bash
rule augmented_line_connections:
    input: resources/CD/costs.csv, networks/CD/elec_s_10_pre_augmentation.nc, resources/CD/bus_regions/regions_onshore_elec_s_10.geojson, resources/CD/bus_regions/regions_offshore_elec_s_10.geojson
    output: networks/CD/elec_s_10.nc
    log: logs/CD/augmented_line_connections/elec_s_10.log
    jobid: 4
    benchmark: benchmarks/CD/augmented_line_connections/elec_s_10
    reason: Missing output files: networks/CD/elec_s_10.nc; Input files updated by another job: resources/CD/bus_regions/regions_onshore_elec_s_10.geojson, resources/CD/bus_regions/regions_offshore_elec_s_10.geojson, networks/CD/elec_s_10_pre_augmentation.nc, resources/CD/costs.csv
    wildcards: simpl=, clusters=10
    resources: tmpdir=/var/folders/qn/vpndfm21795ckkq89np1ckp40000gn/T, mem_mb=3000, mem_mib=2862
INFO:snakemake.logging:rule augmented_line_connections:
    input: resources/CD/costs.csv, networks/CD/elec_s_10_pre_augmentation.nc, resources/CD/bus_regions/regions_onshore_elec_s_10.geojson, resources/CD/bus_regions/regions_offshore_elec_s_10.geojson
    output: networks/CD/elec_s_10.nc
    log: logs/CD/augmented_line_connections/elec_s_10.log
    jobid: 4
    benchmark: benchmarks/CD/augmented_line_connections/elec_s_10
    reason: Missing output files: networks/CD/elec_s_10.nc; Input files updated by another job: resources/CD/bus_regions/regions_onshore_elec_s_10.geojson, resources/CD/bus_regions/regions_offshore_elec_s_10.geojson, networks/CD/elec_s_10_pre_augmentation.nc, resources/CD/costs.csv
    wildcards: simpl=, clusters=10
    resources: tmpdir=/var/folders/qn/vpndfm21795ckkq89np1ckp40000gn/T, mem_mb=3000, mem_mib=2862

INFO:snakemake.logging:
INFO:pypsa.io:Imported network elec_s_10_pre_augmentation.nc has buses, carriers, generators, lines, links, loads, storage_units
Traceback (most recent call last):
  File "~pypsa-earth/.snakemake/scripts/tmp_sfy0l5r.augmented_line_connections.py", line 177, in <module>
    _set_links_underwater_fraction(snakemake.input.regions_offshore, n)
  File "~/Library/Caches/snakemake/snakemake/source-cache/runtime-cache/tmp4zrhwxjf/file~pypsa-earth/scripts/base_network.py", line 157, in _set_links_underwater_fraction
    links = gpd.GeoSeries(n.links.geometry.dropna().map(shapely.wkt.loads))
  File "~/opt/miniconda3/envs/pypsa-earth-upd14/lib/python3.10/site-packages/pandas/core/series.py", line 4397, in map
    new_values = self._map_values(arg, na_action=na_action)
  File "~/opt/miniconda3/envs/pypsa-earth-upd14/lib/python3.10/site-packages/pandas/core/base.py", line 924, in _map_values
    new_values = map_f(values, mapper)
  File "pandas/_libs/lib.pyx", line 2834, in pandas._libs.lib.map_infer
  File "~/opt/miniconda3/envs/pypsa-earth-upd14/lib/python3.10/site-packages/shapely/wkt.py", line 22, in loads
    return shapely.from_wkt(data)
  File "~/opt/miniconda3/envs/pypsa-earth-upd14/lib/python3.10/site-packages/shapely/io.py", line 286, in from_wkt
    return lib.from_wkt(geometry, invalid_handler, **kwargs)
shapely.errors.GEOSException: ParseException: Expected word but encountered end of stream
```

**Comment by ekatef** [comment]
Resolving this issue may be needed to address #192
