### ISSUE TITLE
Handle parallel lines and links in simplify_network

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#791]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

When running the workflow for Africa with the default configuration an error occurs in simplify_network due to parallel DC lines that are connecting the same starting and ending point.
This is a problem related to the handling of simplify_network and the simplify_links procedure.

To handle this issue, there are two approaches:
1. include a preliminary preprocessing in simplify_network that merges lines and links that start and end in the same endpoints. This should also reduce the number of variables and constraints in the problem
2. revise the simplify_link procedure to also handle parallel points

Both steps are welcome :)

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```bash
Traceback (most recent call last):
  File "C:\Users\\miniconda3\envs\pypsa-earth\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\\miniconda3\envs\pypsa-earth\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\\.vscode\extensions\ms-python.python-2023.12.0\pythonFiles\lib\python\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\\.vscode\extensions\ms-python.python-2023.12.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main  
    run()
  File "c:\Users\\.vscode\extensions\ms-python.python-2023.12.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\\.vscode\extensions\ms-python.python-2023.12.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\\.vscode\extensions\ms-python.python-2023.12.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\\.vscode\extensions\ms-python.python-2023.12.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "c:\Users\\Desktop\ppypsatest\pypsa-earth\scripts\simplify_network.py", line 810, in <module>
    n, simplify_links_map = simplify_links(
  File "c:\Users\\Desktop\ppypsatest\pypsa-earth\scripts\simplify_network.py", line 401, in simplify_links
    i_links = [i for _, i in dc_edges if _ == "Link"]
  File "c:\Users\\Desktop\ppypsatest\pypsa-earth\scripts\simplify_network.py", line 401, in <listcomp>
    i_links = [i for _, i in dc_edges if _ == "Link"]
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by ekatef** [comment]
Hey @davide-f! Sounds very interesting. Is it possible to give some hints on how to reproduce this error in possibly minimal model configuration?

**Comment by davide-f** [comment]
I think this issue was solved in the latest PR on fixing the execution for africa.
https://github.com/pypsa-meets-earth/pypsa-earth/pull/792

Merging parallel lines and links may be a nice simplification for computational elements but it is not a priority.
This issue can be closed. If you disagree, feel free to reopen it :)

**Comment by ekatef** [comment]
> I think this issue was solved in the latest PR on fixing the execution for africa. #792
> 
> Merging parallel lines and links may be a nice simplification for computational elements but it is not a priority. This issue can be closed. If you disagree, feel free to reopen it :)

Thanks a lot for the update! I'm totally aligned with the lower-priority status we agreed initially. I just had an impression that it could get more pressing due to some region-related issues. As that's not the case, let's stick to the initial plan :)
