### ISSUE TITLE
Error in build_shapes

### ISSUE THREAD

**Issue by ariannaleoni** [pz-max/pypsa-africa#984]
## Checklist

- [x ] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x ] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug
Hello, 

I'm trying to conduct a simulation of the African continent using PyPSA-Earth, but I'm encountering an issue with build_shapes. I suspect the problem lies with the _simplify_polys function, which seems to fail in creating the polygons, thereby causing the code to break. Although I've tried to make modifications, I've encountered additional issues during the simulation, which may be partly caused to my changes.
Instead of the original line return polys.simplify(tolerance=tolerance) (line 257), I've made the following adjustment:

counter = 0
while counter < 100:
try:
return polys.simplify(tolerance=tolerance)
except Exception as e:
counter += 1
[logger.info](http://logger.info/)(counter)
pass

I cannot reproduce the issue since I don't have another machine, but I have conducted multiple simulations using the same model settings and the error remain always consistent. However, I copied the config.default.yaml file, renamed it as config.yaml, and inserted "Africa" under countries and "100" for the cluster parameter. I have tried to use in the simulation both cutout-2013-era5 and africa-2013-era5. I left the values of the other parameters unchanged. When running the simulation without modifying _simplify_polys, the error message received is as follows:

## Error Message

```bash
Error in rule build_shapes:
jobid: 10
input: data/eez/eez_v11.gpkg
output: resources/shapes/country_shapes.geojson, resources/shapes/offshore_shapes.geojson, resources/shapes/africa_shape.geojson, resources/shapes/gadm_shapes.geojson
log: logs/build_shapes.log (check log file(s) for error details)

ERROR:snakemake.logging:Error in rule build_shapes:
jobid: 10
input: data/eez/eez_v11.gpkg
output: resources/shapes/country_shapes.geojson, resources/shapes/offshore_shapes.geojson, resources/shapes/africa_shape.geojson, resources/shapes/gadm_shapes.geojson
log: logs/build_shapes.log (check log file(s) for error details)

RuleException:
CalledProcessError in file /Users/ariannaleoni/pypsa-earth-project/pypsa-earth/Snakefile, line 259:
Command 'set -euo pipefail; /Users/ariannaleoni/miniconda3/envs/pypsa-earth/bin/python3.10 /Users/ariannaleoni/pypsa-earth-project/pypsa-earth/.snakemake/scripts/tmp_9x785vx.build_shapes.py' returned non-zero exit status 1.
File "/Users/ariannaleoni/pypsa-earth-project/pypsa-earth/Snakefile", line 259, in __rule_build_shapes
File "/Users/ariannaleoni/miniconda3/envs/pypsa-earth/lib/python3.10/concurrent/futures/thread.py", line 58, in run
ERROR:snakemake.logging:RuleException:
CalledProcessError in file /Users/ariannaleoni/pypsa-earth-project/pypsa-earth/Snakefile, line 259:
Command 'set -euo pipefail; /Users/ariannaleoni/miniconda3/envs/pypsa-earth/bin/python3.10 /Users/ariannaleoni/pypsa-earth-project/pypsa-earth/.snakemake/scripts/tmp_9x785vx.build_shapes.py' returned non-zero exit status 1.
File "/Users/ariannaleoni/pypsa-earth-project/pypsa-earth/Snakefile", line 259, in __rule_build_shapes
File "/Users/ariannaleoni/miniconda3/envs/pypsa-earth/lib/python3.10/concurrent/futures/thread.py", line 58, in run

```
And in the log file:

```bash
ERROR:_helpers:An error happened in module '/Users/ariannaleoni/miniconda3/envs/pypsa-earth/lib/python3.10/site-packages/shapely/constructive.py', function 'simplify': IllegalArgumentException: CGAlgorithmsDD::orientationIndex encountered NaN/Inf numbers
Traceback (most recent call last):
File "/Users/ariannaleoni/pypsa-earth-project/pypsa-earth/.snakemake/scripts/tmp_9x785vx.build_shapes.py", line 1342, in 
offshore_shapes = eez(
File "/Users/ariannaleoni/pypsa-earth-project/pypsa-earth/.snakemake/scripts/tmp_9x785vx.build_shapes.py", line 391, in eez
ret_df = ret_df.geometry.map(
File "/Users/ariannaleoni/miniconda3/envs/pypsa-earth/lib/python3.10/site-packages/pandas/core/series.py", line 4691, in map
new_values = self._map_values(arg, na_action=na_action)
File "/Users/ariannaleoni/miniconda3/envs/pypsa-earth/lib/python3.10/site-packages/pandas/core/base.py", line 919, in _map_values
return arr.map(mapper, na_action=na_action)
File "/Users/ariannaleoni/miniconda3/envs/pypsa-earth/lib/python3.10/site-packages/pandas/core/arrays/base.py", line 2319, in map
return map_array(self, mapper, na_action=na_action)
File "/Users/ariannaleoni/miniconda3/envs/pypsa-earth/lib/python3.10/site-packages/pandas/core/algorithms.py", line 1743, in map_array
return lib.map_infer(values, mapper, convert=convert)
File "lib.pyx", line 2972, in pandas._libs.lib.map_infer
File "/Users/ariannaleoni/pypsa-earth-project/pypsa-earth/.snakemake/scripts/tmp_9x785vx.build_shapes.py", line 392, in 
lambda x: _simplify_polys(x, minarea=minarea, tolerance=tolerance)
File "/Users/ariannaleoni/pypsa-earth-project/pypsa-earth/.snakemake/scripts/tmp_9x785vx.build_shapes.py", line 261, in _simplify_polys
return polys.simplify(tolerance=tolerance)
File "/Users/ariannaleoni/miniconda3/envs/pypsa-earth/lib/python3.10/site-packages/shapely/geometry/base.py", line 564, in simplify
return shapely.simplify(self, tolerance, preserve_topology=preserve_topology)
File "/Users/ariannaleoni/miniconda3/envs/pypsa-earth/lib/python3.10/site-packages/shapely/decorators.py", line 77, in wrapped
return func(*args, **kwargs)
File "/Users/ariannaleoni/miniconda3/envs/pypsa-earth/lib/python3.10/site-packages/shapely/constructive.py", line 862, in simplify
return lib.simplify_preserve_topology(geometry, tolerance, **kwargs)
shapely.errors.GEOSException: IllegalArgumentException: CGAlgorithmsDD::orientationIndex encountered NaN/Inf numbers


```

**Comment by ekatef** [comment]
Hello @ariannaleoni, thank you for the discussion and opening the issue. Could you please update its status?

**Comment by ekatef** [comment]
Hello @ariannaleoni I'm closing this issue as it's not quite clear how to reproduce it. Please feel free to reopen if you think otherwise!
